services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streamlit

  streamlit:
    build: ./frontend
    container_name: streamlit
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/app
    command: streamlit run /app/app.py --server.port 8001

  fastapi:
    build: ./backend
    container_name: fastapi
    ports:
      - "8050:8050"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8050
