services:
  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      TZ: Asia/Seoul
    ports:
      - "8050:8050"

  streamlib:
    build: ./frontend
    container_name: streamlib
    environment:
      TZ: Asia/Seoul
    ports:
      - "8001:8001"

volumes:
  db_data: