services:
  fastapi:
    build: ./backend
    container_name: fastapi
    environment:
      TZ: Asia/Seoul
    ports:
      - "8050:8050"

  streamlib:
    build: ./frontend
    container_name: streamlib
    environment:
      TZ: Asia/Seoul
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - fastapi

volumes:
  db_data:
