name: Deploy Application

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 리포지토리 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. sshpass 설치 (비밀번호 기반 SSH 사용)
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    # 3. 서버에 접속하여 Docker Compose로 애플리케이션 배포
    - name: Deploy with SSH and Password
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/ai_ibm
          docker-compose down 
          docker-compose pull 
          docker-compose up -d --remove-orphans 
        EOF
