name: Deploy Application

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시할 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 리포지토리 체크아웃
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Save SSH Private Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # 3. 서버에 접속하여 Docker Compose로 애플리케이션 배포
    - name: Deploy with Docker Compose
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ibmuser03@165.192.86.245 << 'EOF'
          cd /home/ibmuser01/ai_ibm
          docker-compose down 
          docker-compose pull 
          docker-compose up -d --remove-orphans 
        EOF
